export const HELP_CATEGORIES: string[] = [
  'General',
  'Programming',
  'Web Development',
  'App Development',
  'Frontend Development',
  'Backend Development',
  'Full Stack Development',
  'Java',
  'Python',
  'C Programming',
  'C++',
  'JavaScript',
  'TypeScript',
  'React',
  'Node.js',
  'Data Structures',
  'Algorithms',
  'Object-Oriented Programming',
  'Database',
  'SQL',
  'DBMS',
  'Operating Systems',
  'Computer Networks',
  'Software Engineering',
  'Git & GitHub',
  'UI/UX Design',
  'Figma',
  'Graphic Design',
  'AI/ML',
  'Data Science',
  'Deep Learning',
  'Computer Vision',
  'NLP',
  'Cybersecurity',
  'Ethical Hacking',
  'Cloud Computing',
  'DevOps',
  'IoT',
  'Robotics',
  'Electronics',
  'Arduino',
  'Embedded Systems',
  'Mathematics',
  'Engineering Mathematics',
  'Physics',
  'Chemistry',
  'English',
  'Communication Skills',
  'Presentation Skills',
  'Aptitude',
  'Reasoning',
  'Placement Prep',
  'Resume Review',
  'Interview Prep',
  'Internship Guidance',
  'Project Help',
  'Research Paper Help',
  'Documentation Help',
  'Exam Preparation',
  'Assignment Help',
  'Lab Work',
  'Other',
];
